### ISSUE TITLE
Use mask a 2D collider

### ISSUE THREAD

**Issue by gonzamoiguer** [keijiro/NNCam2#2]
First of all, thanks for all the amazing code you always provide.
I have a question, of course Im not asking for code, but for directions. Above all the effects you do, I want to use the BodyPix mask to create a 2D collider. I've been looking at some blob to shape code but not working yet. Is there something like that you are already doing somewhere? You do think CPU can handle that or should I approach at a compute shader? Thanks a lot any directions will be helpful.

**Comment by keijiro** [comment]
> Is there something like that you are already doing somewhere? 

No.

> You do think CPU can handle that or should I approach at a compute shader? 

I don't know any GPU-friendly triangulation algorithm. I'm not sure but under the impression that GPU doesn't help it.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problem.
