### ISSUE TITLE
 modifying and using this project

### ISSUE THREAD

**Issue by yaqqolerz** [keijiro/NNCam2#4]
Hello, i came here because i'm interested in using bodypix and this nncam project.
i'm new to bodypix and barracuda, but i wanted to learn to modify this project.
is there any guide on how to modify assets such as the eye filter, electric filter, etc?
and also how do i change the keybinds and what keys already been bound (i only managed to find that the only key works are q,w,1,2,3)? thanks!

**Comment by keijiro** [comment]
Unfortunately, I can't spend time for explaining them because I forgot almost everything about this project (I created it two years ago and I have other 790 project on GitHub -- I can't remember details about a specific single project). I'd appreciate if you could spend your time to investigate it.
